/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package zedi.pacbridge.messagedecoder.ui;


import java.awt.AWTEvent;
import java.awt.Dimension;

import javax.swing.JFrame;

import zedi.pacbridge.utl.NotificationCenter;
import zedi.pacbridge.utl.StringUtilities;
import zedi.swingutl.beans.ConsoleTextPane;
import zedi.swingutl.beans.utl.SwingUtl;
import java.awt.Font;

/**
 *
 * @author daver
 */
public class MainWindow extends javax.swing.JFrame {
    public final static String DECODE_BYTES_NOTIFICATION = "DecodeBytes";

    private final NotificationCenter notificationCenter;

    public MainWindow(NotificationCenter notificationCenter) {
        this.notificationCenter = notificationCenter;
        setSize(new Dimension(700, 500));
        initComponents();
        stpMenuItem.setSelected(true);
        stpMenuItem.setEnabled(false);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        enableEvents(AWTEvent.WINDOW_EVENT_MASK);
    }

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        this(new NotificationCenter());
    }

    public ConsoleTextPane getOutputTextPane() {
        return outputTextPane;
    }

    public ConsoleTextPane getTraceTextPane() {
        return traceTextPane;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        mainPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        bytesTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        outputScrollPane = new javax.swing.JScrollPane();
        outputTextPane = new zedi.swingutl.beans.ConsoleTextPane();
        outputTextPane.setFont(new Font("Courier", Font.PLAIN, 12));
        traceScrollPane = new javax.swing.JScrollPane();
        traceTextPane = new zedi.swingutl.beans.ConsoleTextPane();
        traceTextPane.setFont(new Font("Courier", Font.PLAIN, 12));
        statusPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        protocolMenu = new javax.swing.JMenu();
        zapMenuItem = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        stpMenuItem = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(bytesTextField, java.awt.BorderLayout.CENTER);

        jLabel1.setText("Bytes:");
        jPanel1.add(jLabel1, java.awt.BorderLayout.LINE_START);

        submitButton.setText("Decode");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(submitButton, java.awt.BorderLayout.LINE_END);

        mainPanel.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jSplitPane1.setDividerLocation(300);
        jSplitPane1.setDividerSize(10);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        outputScrollPane.setViewportView(outputTextPane);

        jSplitPane1.setLeftComponent(outputScrollPane);

        traceScrollPane.setViewportView(traceTextPane);

        jSplitPane1.setRightComponent(traceScrollPane);

        mainPanel.add(jSplitPane1, java.awt.BorderLayout.CENTER);

        statusPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        statusPanel.setLayout(new java.awt.GridLayout(1, 0));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Protocol: ZAP");
        jPanel2.add(jLabel2, java.awt.BorderLayout.CENTER);

        statusPanel.add(jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel3.setText("Messages: ZAP");
        jPanel3.add(jLabel3, java.awt.BorderLayout.CENTER);

        statusPanel.add(jPanel3);

        mainPanel.add(statusPanel, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");

        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(exitMenuItem);

        jMenuBar1.add(jMenu1);

        protocolMenu.setText("Decoders");

        zapMenuItem.setText("Protocol");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("ZAP");
        jRadioButtonMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem1ActionPerformed(evt);
            }
        });
        zapMenuItem.add(jRadioButtonMenuItem1);

        stpMenuItem.setSelected(true);
        stpMenuItem.setText("STP");
        zapMenuItem.add(stpMenuItem);

        protocolMenu.add(zapMenuItem);

        jMenuBar1.add(protocolMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        String text = bytesTextField.getText().trim();
        if (StringUtilities.isValidInputString(text))
            notificationCenter.postNotification(DECODE_BYTES_NOTIFICATION, text);
        bytesTextField.setText("");
    }//GEN-LAST:event_submitButtonActionPerformed

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void jRadioButtonMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel. For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                SwingUtl.initLookAndFeel();
                MainWindow mainWindow = new MainWindow();
                mainWindow.setSize(new Dimension(700, 500));
                SwingUtl.centerFrameInScreen(mainWindow);
                mainWindow.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bytesTextField;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JScrollPane outputScrollPane;
    private zedi.swingutl.beans.ConsoleTextPane outputTextPane;
    private javax.swing.JMenu protocolMenu;
    private javax.swing.JPanel statusPanel;
    private javax.swing.JRadioButtonMenuItem stpMenuItem;
    private javax.swing.JButton submitButton;
    private javax.swing.JScrollPane traceScrollPane;
    private zedi.swingutl.beans.ConsoleTextPane traceTextPane;
    private javax.swing.JMenu zapMenuItem;
    // End of variables declaration//GEN-END:variables
}
